services:
  database:
    image: docker.io/library/mariadb:12

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: unibite
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - ./data/mariadb:/var/lib/mysql

  api:
    image: docker.io/library/node:26-alpine
    working_dir: /app

    volumes:
      - ./api:/app
      - ./data/sessions:/app/sessions
      - ./data/uploads:/app/uploads
      - /app/node_modules

    command: sh -c "npm install && npm start"

    # requests to the api are redirected to
    # this container by the Nginx reverse proxy
    #ports:
    #  - "3000:3000"

    environment:
      CHOKIDAR_USEPOLLING: "true"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}

  web:
    image: docker.io/library/nginx:alpine

    depends_on:
      - api

    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/uploads:/usr/share/nginx/html/uploads:ro

    ports:
      - "8080:80"
